import type { Metadata } from 'next'

import type { ReactNode } from 'react'

import { Inter } from 'next/font/google'

import { Header } from '@/shared/components'
import { Providers } from '@/shared/providers/Providers'

import '@/shared/styles/index.scss'

const inter = Inter({
  variable: '--font-inter',
  subsets: ['latin', 'cyrillic'],
  display: 'swap',
  weight: ['400', '500', '600', '700'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode
}>) {
  return (
    <html lang={'en'}>
      <body className={`${inter.className}`}>
        <Providers>
          <Header />
          {children}
        </Providers>
      </body>
    </html>
  )
}
